# Redirección para el sitemap dinámico
[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/generate-sitemap"
  status = 200

# Redirección para aplicaciones de una sola página (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración para la función de fondo.
# El nombre "generate-concepts-background" debe coincidir con el nombre del archivo de la función.
[functions."generate-concepts-background"]
  background = true
